# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/uart_fifo/uart_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_fifo || ORIG_REF_NAME==uart_fifo}]
