# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/user/fpga_projects/karatsuba/karatsuba.cache/wt [current_project]
set_property parent.project_path /home/user/fpga_projects/karatsuba/karatsuba.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo /home/user/fpga_projects/karatsuba/karatsuba.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/user/fpga_projects/src/rs232_rx.v
  /home/user/fpga_projects/src/rs232_tx.v
  /home/user/fpga_projects/src/uart_txrx.v
  /home/user/fpga_projects/src/top.v
}
read_vhdl -library xil_defaultlib {
  /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/new/multiplication_wrapper.vhd
  /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/new/multiplier.vhd
  /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/imports/src_simple/polynom_multiplier.vhd
  /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/new/reduction.vhd
}
read_ip -quiet /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/ip/uart_fifo/uart_fifo.xci
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/ip/uart_fifo/uart_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/ip/uart_fifo/uart_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/ip/uart_fifo/uart_fifo_ooc.xdc]
set_property is_locked true [get_files /home/user/fpga_projects/karatsuba/karatsuba.srcs/sources_1/ip/uart_fifo/uart_fifo.xci]

read_ip -quiet /home/user/fpga_projects/src/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /home/user/fpga_projects/src/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet /home/user/fpga_projects/src/microblaze_mcs_0/microblaze_mcs_0.xci
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/ip/ip_9/bd_fc5c_0_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/microblaze_mcs_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/fpga_projects/src/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc]
set_property is_locked true [get_files /home/user/fpga_projects/src/microblaze_mcs_0/microblaze_mcs_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
